[global]
keyboard = "jp"
country = "jp"
fqdn = "nonoka.home-cloud.internal"
mailto = "mail@example.com"
timezone = "Asia/Tokyo"
root-password = "1qaz!QAZ"

[network]
source = "from-answer"
cidr = "192.168.30.4/24"
dns = "192.168.30.1"
gateway = "192.168.30.1"
filter.ID_NET_NAME = "enp5s0"

[disk-setup]
filesystem = "ext4"
lvm.swapsize = 0
disk-list = ["sda"]
